# Generated by Django 3.2.9 on 2021-12-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rate', models.PositiveIntegerField()),
                ('fare', models.PositiveIntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('room_amenities', models.TextField()),
                ('city', models.CharField(max_length=250)),
                ('adults', models.PositiveIntegerField(blank=True, null=True)),
                ('dateFrom', models.DateField(auto_now_add=True, null=True)),
                ('dateTo', models.DateField(auto_now=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.provider')),
            ],
            options={
                'ordering': ['-rate'],
            },
        ),
    ]
