# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
