# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180405_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
