# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 27, 17, 52, 7, 154752))),
            ],
        ),
    ]
