/*
	appendChild  > add new element as a child of parent element (elements, text)
*/


var myDiv = document.getElementById('test'),
	myNewDiv = document.createElement('div'),
	myNewP = document.createElement('p'),
	myText = document.createTextNode('Text Generated by JavaScript');


myNewDiv.appendChild(myText);
myDiv.appendChild(myNewDiv);
myDiv.appendChild(myNewP);
