/*
	insertBefore(element, index)  > add new element as a child of parent element (element only)
*/


var myDiv = document.getElementById('test'),
	myNewDiv = document.createElement('div'),
	myText = document.createTextNode('Text Generated by JavaScript');


myNewDiv.appendChild(myText);

myDiv.insertBefore(myNewDiv, myDiv.firstElementChild);
myDiv.insertBefore(myNewDiv, myDiv.childNodes[0]);
myDiv.insertBefore(myNewDiv, myDiv.children[0]);
