# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 20:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('fayoum', django.db.models.manager.Manager()),
            ],
        ),
    ]
