# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='sound',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
