# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-30 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180630_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%Y-%m-%d'),
        ),
    ]
