# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180630_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to=posts.models.get_image_path),
        ),
    ]
