# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180630_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='block_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
