# Generated by Django 4.2.6 on 2023-10-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(default='92660', max_length=120),
        ),
    ]
