# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurantlocation_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='owner',
            new_name='user',
        ),
    ]
