# Generated by Django 4.2.6 on 2023-10-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products_two.product',),
        ),
    ]
