# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 12:27
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180529_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to=accounts.models.get_image_path),
        ),
    ]
