# Generated by Django 4.2.6 on 2023-10-28 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_remove_car_user_car_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='drivers',
        ),
        migrations.AddField(
            model_name='car',
            name='first_owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
