# Generated by Django 4.2.6 on 2023-10-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_three', '0003_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default='2023-10-26'),
        ),
    ]
