# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180405_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
