# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180405_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.BinaryField(null=True),
        ),
    ]
