# Generated by Django 4.2.6 on 2023-10-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=240, verbose_name='Post Title')),
                ('content', models.TextField(blank=True, null=True)),
                ('publish', models.CharField(choices=[('DR', 'Draft'), ('PU', 'Publish'), ('PR', 'Private')], default='draft', max_length=120)),
            ],
        ),
    ]
