# Generated by Django 4.2.6 on 2023-10-15 17:19

import blog_two.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_two', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[blog_two.models.validate_author_email]),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=240, unique=True, verbose_name='Post Title'),
        ),
    ]
