# Generated by Django 4.2.6 on 2023-10-15 17:24

import blog_two.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_two', '0002_post_author_email_post_publish_date_post_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True, validators=[blog_two.validators.validate_author_email]),
        ),
    ]
