# Generated by Django 4.2.6 on 2023-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_two', '0003_alter_post_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
