# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180103_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=250, validators=[shortener.validators.validate_url, shortener.validators.validate_domain]),
        ),
    ]
