# Generated by Django 4.2.6 on 2023-10-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_timestamp_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
