# Generated by Django 4.2.6 on 2023-10-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_publish_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
